
name: Build & Deployment

on: 
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Start SSH Agent
        run: |
          eval `ssh-agent`


      - name: Debug SSH Agent Environment Variables
        run: |
          echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
          echo "SSH_AGENT_PID: $SSH_AGENT_PID"

      - name: Add SSH Key to Agent
        run: |
          ssh-add /home/runner/.ssh/github
          
      - name: Check SSH Agent Status
        run: |
          ssh-add -l

          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        
      - name: Install Dependencies
        run: npm install

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_SECRET }}
          external_repository: MohammedAltarkawi/mohammedaltarkawi.github.io
          publish_branch: main  # default: gh-pages
          publish_dir: ./public
          keepFiles: false
